Algoritmo "1p12"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : dr Ticongolo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matimbe Jose
// Data atual  : 01/02/2022
Var
   // Seção de Declarações das variáveis
   i : inteiro
   an : real



Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para i <- 0 ate 100 faca
      an <- 2*i + 1
      escreva(an)
   fimpara


Fimalgoritmo